tap "nikitabobko/tap"

# Shell, navigation, and source control
brew "atuin"
brew "bat"
brew "direnv"
brew "eza"
brew "fd"
brew "fnm"
brew "fzf"
brew "fzf-tab"
brew "gh"
brew "git"
brew "jq"
brew "lazygit"
brew "pnpm"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tmux"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Editor and language tooling
brew "neovim"
brew "ruff"
brew "shfmt"
brew "stylua"
brew "taplo"
brew "tree-sitter-cli"
brew "ty"
brew "uv"

# Keep the existing terminal/window-manager setup and appearance.
cask "nikitabobko/tap/aerospace"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "wezterm@nightly"
