set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g prefix C-f
unbind C-b
bind-key C-f send-prefix

unbind %
bind | split-window -h 

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"
set -g base-index 1

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind -r m resize-pane -Z

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

# remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10

bind-key -r o if-shell "[ -x ~/.local/bin/tmux-sessionizer ] && [ -d ~/.dotfiles/ ]" "run-shell '~/.local/bin/tmux-sessionizer ~/.dotfiles/'" "display-message '~/.dotfiles or tmux-sessionizer missing'"

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'fabioluciano/tmux-tokyo-night'

if-shell 'command -v open >/dev/null 2>&1' 'set -g @open "open"' 'set -g @open "xdg-open"'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

bind-key -r g if-shell "command -v lazygit >/dev/null 2>&1" "new-window -n lazygit lazygit" "display-message 'lazygit not found'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
